butcher = struct('name','butcher',...
  'faction','grineer',...
  'level',1,...
  'shield_type','nan',...
  'shield_value',0,...
  'armor_type', 'ferrite_armor',...
  'armor_value', 5,...
  'health_type', 'cloned_flesh',...
  'health_value', 50);

scorpion = struct('name','scorpion',...
  'faction','grineer',...
  'level',10,...
  'shield_type','nan',...
  'shield_value',0,...
  'armor_type', 'ferrite_armor',...
  'armor_value', 150,...
  'health_type', 'cloned_flesh',...
  'health_value', 150);

ballista = struct('name','ballista',...
  'faction','grineer',...
  'level',1,...
  'shield_type','nan',...
  'shield_value',0,...
  'armor_type', 'ferrite_armor',...
  'armor_value', 100,...
  'health_type', 'cloned_flesh',...
  'health_value', 100);

lancer = struct('name','lancer',...
  'faction','grineer',...
  'level',1,...
  'shield_type','nan',...
  'shield_value',0,...
  'armor_type', 'ferrite_armor',...
  'armor_value', 100,...
  'health_type', 'cloned_flesh',...
  'health_value', 100);